---
  title: "day620"
output:html_document:
date: '2022-06-20'
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 3장
- R in 42~46 page
```{r}
sex <-c("male", "female")
korean <- c(87,92)
english <- c(88,95)
# 명목형 자료형 Factor
locaiton_vector <- c("서울", "인천", "부산")
factor_location_vector <- factor(locaiton_vector)
factor_location_vector

class(factor_location_vector)
help(factor)

# 순서형 자료형 Factor
temperature_factor <- c("기온높음", 
                        "기온보통", 
                        "기온낮음", 
                        "기온높음", 
                        "기온보통", 
                        "기온보통")

temperature_factor

factor_temperature_factor <- factor(temperature_factor, 
                                    ordered = TRUE, 
                                    levels  = c("기온보통", 
                                               "기온낮음", 
                                               "기온높음"))
factor_temperature_factor
class(factor_temperature_factor)
class(factor_location_factor)

## 데이터 프레임
#- 엑설 데이터

no = c(1,2,3,4,5)
sex = c("male", "female", "male", "male", "female")
korean = c(87,92,95,81,87)
exam = data.frame(no, sex, korean)
exam
exam$
exam$sex[1]



```

